### ISSUE TITLE
login from meetecho required to take minutes lands at wrong page

### ISSUE THREAD

**Issue by elear** [ietf-tools/hedgedoc#2]
When one is taking minutes from meetecho, and one clicks on edit and then edits, one is asked to log into the data tracker.  When one does this, one is then redirected not to the minutes page, but to the hedgedoc home page.  The right thing is to redirect back to the minutes page.

**Comment by elear** [comment]
This happened to me during the RSWG meeting.

**Comment by rjsparks** [comment]
This is a consequence of hedgedoc's oidc(ish) integration, and any fix will have to be in the hedgedoc code. That community is focusing on a rewrite of hedgedoc instead. Closing this as won't fix.
